#!/bin/bash

WESNOTH_HOME="/Applications/Wesnoth/Wesnoth.app/Contents/Resources"
TOOLS_DIR="$WESNOTH_HOME/data/tools"
CORE_DIR="$WESNOTH_HOME/data/core"

cd $(dirname 0)
ADD_ON_DIR=$(pwd -P)
echo "$TOOLS_DIR/wmllint" --dryrun "$CORE_DIR" "$ADD_ON_DIR"
"$TOOLS_DIR/wmllint" --dryrun "$CORE_DIR" "$ADD_ON_DIR" 2>&1 | tee $(pwd)/wmllint-run.log
